story1/urls.py
from django.urls import path
from . import views

app_name = "story1"

urlpatterns = [
	path('', views.story1),
]

story3/urls.py
from django.urls import path
from . import views

app_name = "story3"

urlpatterns = [
	path('', views.index),
    path('projects', views.projects),
]

story5/urls.py
from django.urls import path
from django.conf.urls import url
from . import views

app_name = "story5"

urlpatterns = [
	path('', views.course, name="course"),
	path('saveform', views.saveform, name="saveform"),
	path('details/<int:id>', views.details, name="details"),
	path('delete/<int:id>', views.delete, name="delete")
]

storyppw/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('story1/', include('story1.urls')),
    path('', include('story3.urls')),
    path('course/', include('story5.urls'))
]

story1/models.py
from django.db import models

# Create your models here.

story3/models.py
from django.db import models

# Create your models here.

story5/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator

# Create your models here.
class Course(models.Model):
    name = models.CharField(max_length=30)
    lecturer = models.CharField(max_length=50)
    credit = models.IntegerField(
        validators=[
            MinValueValidator(1),
            MaxValueValidator(24)
        ]
    )
    desc = models.TextField()
    term = models.CharField(max_length=30)
    room = models.CharField(max_length=30)

    def __str__(self):
        return self.name

story5/forms.py
from django import forms
from .models import Course

class Input_Form(forms.ModelForm):
    class Meta:
        model = Course
        fields = ['name', 'lecturer', 'credit', 'desc', 'term', 'room']

        name_attr = {
            'type': 'text',
            'placeholder': 'Course name',
        }
        lecturer_attr = {
            'type': 'text',
            'placeholder': 'Lecturer\'s name'
        }
        credit_attr = {
            'placeholder': 'Credits count'
        }
        desc_attr = {
            'type': 'text',
            'placeholder': 'Add description here . . .'
        }
        term_attr = {
            'type': 'text',
            'placeholder': 'ex. Gasal 2019/2020'
        }
        room_attr = {
            'type': 'text',
            'placeholder': 'Room location of the course'
        }

        widgets = {
            'name': forms.TextInput(attrs=name_attr),
            'lecturer': forms.TextInput(attrs=lecturer_attr),
            'credit': forms.NumberInput(attrs=credit_attr),
            'desc': forms.Textarea(attrs=desc_attr),
            'term': forms.TextInput(attrs=term_attr),
            'room': forms.TextInput(attrs=room_attr)
        }

        labels = {
            'name': 'Course',
            'lecturer': 'Lecturer',
            'credit': 'Credits',
            'desc': 'Description',
            'term': 'Term',
            'room': 'Room'
        }

story1/views.py
from django.shortcuts import render

# Create your views here.
def story1(request):
    return render(request, 'story1.html')

story3/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'home.html', {'title':"Hello, I'm Anggito"})

def projects(request):
    return render(request, 'projects.html', {'title':"Projects"})

story5/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.contrib import messages
from .forms import Input_Form
from .models import Course

# Create your views here.
def course(request):
    response = {
        'title': "Course Add | List",
        'input_form': Input_Form,
        'courses': Course.objects.all()
    }
    return render(request, 'course.html', response)

def details(request, id):
    course_obj = get_object_or_404(Course, pk=id)
    course_response = {
        'title': "Course: " + course_obj.name,
        'course': course_obj
    }
    return render(request, 'details.html', course_response)

def delete(request, id):
    course = get_object_or_404(Course, pk=id)
    course.delete()
    messages.success(request, f'Course has been deleted!')
    return HttpResponseRedirect('/course')

def saveform(request):
    form = Input_Form(request.POST or None)
    if (form.is_valid() and request.method == 'POST'):
        form.save()
        messages.success(request, f'Course added to list!')
    else:
        form = Input_Form()
        messages.warning(request, f'Credit must be between 1 and 24!')
    return HttpResponseRedirect('/course')

story1/templates/story1.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <title>My Profile</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" href="{% static 'img/icon2.jpg' %}">

    <link rel="stylesheet" href="{% static 'css/style-story1.css' %}">
</head>
<body>
    <div class="container-out">

        <div class="header">
            <h1>Anggito's Profile...</h1>
        </div>

        <div class="container-in">
            <div class="sidebar">
                <h2 align="center">About Me</h2>

                <img src="{% static 'img/self-photo.jpg' %}" alt="self-photo">
    
                <div class="biodata">
                    <table>
                        <tr>
                            <td><b>Name</b></td>
                            <td>Antonius Anggito Arissaputro</td>
                        </tr>
                        <tr>
                            <td><b>Student ID</b></td>
                            <td>1906292912</td>
                        </tr>
                        <tr>
                            <td><b>Birth Date</b></td>
                            <td>Jakarta, 22<sup>nd</sup> June 2001</td>
                        </tr>
                        <tr>
                            <td><b>Class Of</b></td>
                            <td>2019</td>
                        </tr>
                        <tr>
                            <td><b>Study</b></td>
                            <td>Universitas Indonesia</td>
                        </tr>
                    </table>
                </div>

                <div class="media" align="center">
                    <a href="mailto: antoniusanggito@gmail.com" target="_blank"><img src="{% static 'img/gmail.png' %}" alt="gmail"></a>
                    <a href="https://www.instagram.com/antoniusanggito/" target="_blank"><img src="{% static 'img/instagram.png' %}" alt="instagram"></a>
                    <a href="https://www.linkedin.com/in/antonius-anggito-arissaputro-b6b971195/" target="_blank"><img src="{% static 'img/linkedin.png' %}" alt="linkedin"></a>
                    <a href="https://github.com/antoniusanggito" target="_blank"><img src="{% static 'img/github.svg' %}" alt="github"></a>
                </div>
            </div>
    
            <div class="main">
                <div class="description">
                    <h3>Description</h3>
                    <hr>
                    <p>Second year computer science student, currently taking Web Designing and Programming course.</p>
                    <p>I have various hobbies as listed below. I don't really play many games other than Pokemon.</p>
                </div>

                <div class="hobby">
                    <h3>My Hobbies</h3>
                    <hr>
                    <div class="hobby-in">
                        <img src="{% static 'img/chess.jpg' %}" alt="chess">
                        <div class="overlay">
                            <div class="text">Chess</div>
                        </div>
                    </div>
                    <div class="hobby-in">
                        <img src="{% static 'img/guitar.png' %}" alt="guitar">
                        <div class="overlay">
                            <div class="text">Guitar</div>
                        </div>
                    </div>
                    <div class="hobby-in">
                        <img src="{% static 'img/badminton.jpg' %}" alt="badminton">
                        <div class="overlay">
                            <div class="text">Badminton</div>
                        </div>
                    </div>
                </div>

                <div class="history">
                    <h3>Education History</h3>
                    <hr>
                    <ul>
                        <li>SD Mardi Yuana (2007-2010)</li>
                        <li>SD Strada Wiyatasana (2010-2013)</li>
                        <li>SMP Strada Marga Mulia (2013-2016)</li>
                        <li>SMA Kolese Gonzaga (2016-2019)</li>
                        <li>Universitas Indonesia (2019-now)</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</body>
</html>

story3/templates/home.html
{% extends "base.html" %}

{% load static %}

{% block content %}
    <div id="front-page">
        <div class="row justify-content-center">
            <!-- <img src="{% static 'img/front-photo-widerer.jpg' %}" class="img-fluid front-img" alt="front_photo"> -->
            <h1 class="center-on-img"><span>Hello,</span> I'm Anggito</h1>
            <hr class="center-on-img white-line">
            <h3 class="center-on-img">Computer Science Student || 19</h3>
        </div>
    </div>

    <div id="about">
        <div class="row p-5">
            <div class="col-sm-4 col-sm-offset-0 right-border" align="center">
                <img src="{% static 'img/self-photo-squared.jpg' %}" class="rounded-circle about-img" alt="self-photo">
            </div>
            <div class="col-sm-8 col-sm-offset-0">
                <h2><span>About</span> Me</h2>
                <hr class="mobile-line">
                <p>A second year computer science student of University of Indonesia. Currently learning web development and data structures. Enjoy coding and creating things in tech.</p>
            </div>
        </div>

        <div class="row p-5">
            <div class="col-sm-8 col-sm-offset-0 right-border">
                <h2>More <span>Details</span></h2>
                <hr class="mobile-line">
                <div class="row p-3">
                    <div class="col-sm-4 col-sm-offset-0">
                        <p><b>Full Name</b></p>
                    </div>
                    <div class="col-sm-8 col-sm-offset-0 value">
                        <p>Antonius Anggito Arissaputro</p>
                    </div>
                    <div class="col-sm-4 col-sm-offset-0">
                        <p><b>Date of Birth</b></p>
                    </div>
                    <div class="col-sm-8 col-sm-offset-0 value">
                        <p>June 22<sup>nd</sup> 2001</p>
                    </div>
                    <div class="col-sm-4 col-sm-offset-0">
                        <p><b>Study</b></p>
                    </div>
                    <div class="col-sm-8 col-sm-offset-0 value">
                        <p>University of Indonesia</p>
                    </div>
                    <div class="col-sm-4 col-sm-offset-0">
                        <p><b>Interests</b></p>
                    </div>
                    <div class="col-sm-8 col-sm-offset-0 value">
                        <p>Software Engineering, Cyber Security</p>
                    </div>
                    <br>
                </div>
            
            </div>
            <div class="col-sm-4 col-sm-offset-0 skill">
                <h2 align="center"><span>Skills</span></h2>
                <hr class="mobile-line">
                <div class="row" align="center">
                    <div class="col p-3">
                        <img src="{% static 'img/python.png' %}" class="skill-icon" alt="python-icon">
                    </div>
                    <div class="col p-3">
                        <img src="{% static 'img/java.png' %}" class="skill-icon" alt="java-icon">        
                    </div>
                </div>
                <div class="row" align="center">
                    <div class="col p-3">
                        <img src="{% static 'img/html.png' %}" class="skill-icon" alt="html5-icon">
                    </div>
                    <div class="col p-3">
                        <img src="{% static 'img/css.png' %}" class="skill-icon" alt="css-icon">  
                    </div>
                </div>
                <a href="/projects"><h5 align="right"><i><u>My Projects</u></i><svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
                    viewBox="0 0 512 512" style="enable-background:new 0 0 512 512;" xml:space="preserve">
                    <g>
                        <g>
                            <path d="M491.841,156.427c-19.471-45.946-51.936-85.013-92.786-112.637C358.217,16.166,308.893-0.007,256,0
                                c-35.254-0.002-68.946,7.18-99.571,20.158C110.484,39.63,71.416,72.093,43.791,112.943C16.167,153.779-0.007,203.104,0,256
                                c-0.002,35.255,7.181,68.948,20.159,99.573c19.471,45.946,51.937,85.013,92.786,112.637C153.783,495.834,203.107,512.007,256,512
                                c35.253,0.002,68.946-7.18,99.571-20.158c45.945-19.471,85.013-51.935,112.638-92.785C495.834,358.22,512.007,308.894,512,256
                                C512.002,220.744,504.819,187.052,491.841,156.427z M460.413,342.257c-16.851,39.781-45.045,73.724-80.476,97.677
                                c-35.443,23.953-78.02,37.926-123.936,37.933c-30.619-0.002-59.729-6.218-86.255-17.454
                                c-39.781-16.85-73.724-45.044-97.677-80.475C48.114,344.495,34.14,301.917,34.133,256c0.002-30.62,6.219-59.731,17.454-86.257
                                c16.851-39.781,45.045-73.724,80.476-97.677C167.506,48.112,210.084,34.139,256,34.132c30.619,0.002,59.729,6.218,86.255,17.454
                                c39.781,16.85,73.724,45.044,97.677,80.475c23.953,35.443,37.927,78.02,37.934,123.938
                                C477.864,286.62,471.648,315.731,460.413,342.257z"/>
                        </g>
                    </g>
                    <g>
                        <g>
                            <path d="M398.826,242.084L213.278,119.006c-7.686-5.098-18.049-3-23.147,4.685c-5.099,7.685-3,18.049,4.685,23.147
                                l164.568,109.163L194.815,365.164c-7.686,5.098-9.784,15.461-4.685,23.147c5.099,7.686,15.461,9.784,23.147,4.685l185.548-123.08
                                c4.652-3.086,7.468-8.333,7.468-13.916S403.478,245.17,398.826,242.084z"/>
                        </g>
                    </g>
                    </svg></h5>
                </a>
            </div>
        </div>
    </div>

    <div id="hobby">
        <h2 align="center"><span>My</span> Hobbies</h2>
        <hr class="mobile-line">
        <div class="row justify-content-center p-4">
            <div class="col-sm-4 hobby-section">
                <img src="{% static 'img/chess.jpg' %}" class="img-fluid hobby-img" alt="chessboard">
                <p class="hobby-title">Chess</p>
                <p class="hobby-desc">I've been playing chess since I was little, but just recently playing it more seriously.</p>
            </div>
            <div class="col-sm-4 hobby-section">
                <img src="{% static 'img/guitar.jpg' %}" class="img-fluid hobby-img" alt="guitar">
                <p class="hobby-title">Guitar</p>
                <p class="hobby-desc">I really enjoy playing guitar, especially playing instrumental-only and rock genre.</p>
            </div>
            <div class="col-sm-4 hobby-section">
                <img src="{% static 'img/badminton.jpg' %}" class="img-fluid hobby-img" alt="badimnton">
                <p class="hobby-title">Badminton</p>
                <p class="hobby-desc">I'm not very good at badminton, but it is still my all time favorite sport!</p>
            </div>    
        </div>
    </div>
{% endblock content %}

story3/templates/projects.html
{% extends "base.html" %}

{% load static %}

{% block content %}
    <div class="project">
        <h2>Here are my <span>past projects</span></h2>
        <hr class="orange-line">
        <div class="row justify-content-center">
            <div class="col-sm-4 col-sm-offset-2 project-list">
                <a href="https://github.com/antoniusanggito/web-gonz" target="_blank">
                <h4>Gonzaga Festival <span>Website</span></h4>
                <img src="{% static 'img/gonzfest.jpg' %}" alt="gonzfest-thumbnail">
                <p>I lead a team to create a website for Gonzaga College's yearly festival of 2018.</p>
                <p>Created by using HTML, CSS, JS, and PHP.</p>
                </a>
            </div>
            <div class="col-sm-4 col-sm-offset-2 project-list">
                <a href="https://github.com/antoniusanggito/Pokemon-Lite" target="_blank">
                <h4><span>Pokemon</span>-Lite</h4>
                <img src="{% static 'img/pokemonlite.jpg' %}" alt="pokemonlite-thumbnail">
                <p>A lite command line - based of pokemon gba adventure game. Trying to implement as many things as possible into the program.</p>
                <p>Created by using Python.</p>
                </a>
            </div>
            <div class="col-sm-4 col-sm-offset-2 project-list">
                <a href="https://github.com/garyteofanus/pokeproject" target="_blank">
                <h4>Poke<span>Project</span></h4>
                <img src="{% static 'img/pokeproject.png' %}" alt="pokeproject-thumbnail">
                <p>My Foundation of Programming 2 group's mini project. Creating a website that implements Pokemon API in making fun trivia.</p>
                <p>Created by using Java, Springboot, Thymeleaf, HTML, and CSS</p>
                </a>
            </div>
            <div class="col-sm-4 col-sm-offset-2 align-self-center project-list">
                <h2 style="margin: 50% 20px;"><span>More</span> Coming Soon <span>. . .</span></h2>
                </a>
            </div>
        </div>
    </div>
{% endblock content %}

story5/templates/course.html
{% extends "base.html" %}

{% load static %}

{% load crispy_forms_tags %}

{% block content %}
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-{{ message.tags }}">
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}
    <div class="form">
        <div class="form-section">
            <h2 align="center">Course Add <span>Form</span></h2>
            <hr class="orange-line">
            <form action="saveform" method="POST">
                {% csrf_token %}
                {{ input_form|crispy }}
                <input class="btn-submit" type="submit" value="Submit">
            </form>
        </div>
    </div>
    <div class="course">
        {% if courses %}
            <h2 align="center">Course <span>List</span></h2>
            <hr class="orange-line">
            <div class="row">
                {% for course in courses %}
                    <div class="col-sm-4 col-sm-offset-0 course-section">
                        <div class="row">
                            <div class="col">
                                <h4>{{ course.name }}</h4>
                                <a href="{% url 'story5:details' course.id %}">Details</a>
                            </div>
                        </div>
                        <hr color="lightgrey">
                        <ul>
                            <li><b>Lecturer:</b> {{ course.lecturer }}</li>
                            <li><b>Description:</b> {{ course.desc }}</li>
                        </ul>
                    </div>
                {% endfor %}
            </div>
        {% endif %}
    </div>
{% endblock content %}

story5/templates/details.html
{% extends "base.html" %}

{% load static %}

{% block content %}
    <div class="details">
        <div class="details-section">
            <div class="details-title">
                <h2 align="center">{{ course.name }}</h2>
            </div>
            <div class="row">
                <div class="col-sm-6 col-sm-6-offset-0 key">
                    <b>Lecturer</b>
                </div>
                <div class="col-sm-6 col -sm-6-offset-0 value">
                    {{ course.lecturer }}
                </div>
            </div>
            <div class="row">
                <div class="col-sm-6 col-sm-6-offset-0 key">
                    <b>Credit</b>
                </div>
                <div class="col-sm-6 col-sm-6-offset-0 value">
                    {{ course.credit }}
                </div>
            </div>
            <div class="row">
                <div class="col-sm-6 col-sm-6-offset-0 key">
                    <b>Description</b>
                </div>
                <div class="col-sm-6 col-sm-6-offset-0 value">
                    {{ course.desc }}
                </div>
            </div>
            <div class="row">
                <div class="col-sm-6 col-sm-6-offset-0 key">
                    <b>Term</b>
                </div>
                <div class="col-sm-6 col-sm-6-offset-0 value">
                    {{ course.term }}
                </div>
            </div>
            <div class="row">
                <div class="col-sm-6 col-sm-6-offset-0 key">
                    <b>Room</b>
                </div>
                <div class="col-sm-6 col-sm-6-offset-0 value">
                    {{ course.room }}
                </div>
            </div>
            <div class="row" align="center">
                <div class="col m-4">
                    <a href="/course" class="btn-back">Back</a>
                    <a href="{% url 'story5:delete' course.id %}" class="btn-delete">Delete</a>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}